import "./globals.css";

export const metadata = {
  title: "Empanadas",
  description: "Generated by Ezequiel Gómez de Lima",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
